print("Wednesday 14, January 2026")
print("Dear Romel: ")
print("")
print("Hello! You are just starting your Python journey, you're excited but at the same time scared.")
print("You are a really talented guy that even if he fails tries and tries again.")
print("")
print("I can't say for sure that you will complete this learning journey on the first try, ")
print("however im confident that you will be able to learn Python and be succesful eventually.")
print("Please, never give up, always do your best and remember your goals.")
print("")
print("Love you! ❤💥")